networks:
  default:
    name: roboshop
    external: true

services:
  mongodb:
    image: mongodb:v1
    ports:
      - "27017:27017"

  catalogue:
    image: catalogue:v1
    depends_on:
      - mongodb

  web:
    image: web:v1
    ports:
      - "80:80"
    depends_on:
      - catalogue
