version: "3.8"

networks:
  default:
    external:
      name: roboshop

services:
  mongodb:
    image: mongodb:v1
    ports:
      - "27017:27017"
    networks:
      - default

  catalogue:
    image: catalogue:v1
    depends_on:
      - mongodb
    networks:
      - default

  web:
    image: web:v1
    ports:
      - "80:80"
    depends_on:
      - catalogue
    networks:
      - default
