networks:
  default:
    name: roboshop
    external: true

services:
  mongodb:
    image: mongodb:1
    ports:
      - "27017:27017"

  catalogue:
    image: catalogue:1
    depends_on:
      - mongodb

  web:
    image: web:1
    ports:
      - "80:80"
    depends_on:
      - catalogue
  
  redis:
    image: redis

  user:
    image: user:1
    depends_on:
    - redis
    - mongodb
  
  cart:
    image: cart:1
    depends_on:
    - redis
    - catalogue
  mysql:
    image: mysql:1